<div id="backfooter"></div>
<div id="footer">
	<div id="footercont">
  <div id="footerL">
		<div id="laEmpresa">
			<h3>La Empresa</h3>
			<ul>
				<li>Contacto</li>
				<li><a href="blog">Prensa / Blog</a></li>
				<li><a href="sumate">Sumate a TuMovida</a></li>
			</ul>
		</div>
		<div id="conoceMas">
			<h3>Conocé más</h3>
			<ul>
				<li><a target="_blank" href="http://www.youtube.com/watch?v=1gkd3bSVESE">Como funciona TuMovida</a></li>
				<li><a href="info/terminos_y_condiciones">Terminos y condiciones</a></li>
			</ul>
		</div>
	</div>
	<div id="footerR">
		<h3>Compra 100% Segura.</h3>
		<img src="images/logos/redpagos.gif" alt="RedPagos" />
		<span>copyright 2012 - tumovida.com.uy</span>
	</div>
    </div>
</div>